### PR TITLE
Extend FollowPath action feedback

### PR DESCRIPTION
**Pull request by astumpf**
Adding distance_to_goal_point and time_to_goal_point fields. Please check for side effects and merge :-).

### CODE REVIEW

**Comment by StefanFabian** [comment]
Apart from having to rebuild the packages and to ensure an equal state on the robots and our machines I don't see any possible side effects caused by this change.

**Comment by Martin-Oehler** [comment]
This PR targets the wrong branch though, we are on master.

**Comment by astumpf** [comment]
But we are not for some reason :-). Thx!

**Comment by Martin-Oehler** [comment]
I also added your commit to the master branch.

**Pull request merged**
